#!/usr/bin/env python3
"""
Anchor seeder for Bahasa Inggeris — English language only.
All questions generated by Claude Code. No external AI API required.
Run: python seed_english_anchors.py
"""

import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from agents.orchestrator import supabase

SUBJECT = "Bahasa Inggeris"
LANGUAGE = "English"
FALLBACK_AUDIO = "https://cdn.kuasaprestij.tech/assets/fallback_beat.mp3"
FALLBACK_VIDEO = "https://cdn.kuasaprestij.tech/assets/fallback_video.mp4"

ANCHORS = [
    {
        "topic": "Friendships and Relationships",
        "mnemonic_lyrics": (
            "Trust and respect, the friendship code,\n"
            "Listen and share, lighten the load,\n"
            "Empathy glows when you walk in their shoes,\n"
            "Real friends stay true no matter what you choose."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Menganalisis",
            "illustrative_notes": (
                "Friendships are built on trust, mutual respect, and empathy. "
                "Understanding how to maintain healthy relationships requires recognising qualities like loyalty, honesty, and communication. "
                "Think about what distinguishes a genuine friendship from a superficial one."
            ),
            "question": (
                "Aiman always listens patiently when his friend Danial is upset "
                "and offers helpful advice without judging him. "
                "Which quality BEST describes Aiman's behaviour in this friendship?"
            ),
            "options": [
                "Overprotectiveness",
                "Empathy",
                "Jealousy",
                "Independence",
            ],
            "correct_answer": "Empathy",
            "distractor_rationale": {
                "Overprotectiveness": (
                    "Overprotectiveness involves restricting a friend's freedom, not listening without judgement — "
                    "Aiman shows no sign of controlling Danial."
                ),
                "Jealousy": (
                    "Jealousy is a negative emotion involving resentment; "
                    "the passage describes caring and supportive behaviour."
                ),
                "Independence": (
                    "Independence refers to self-reliance, not the act of listening and supporting another person."
                ),
            },
        },
    },
    {
        "topic": "Environment and Nature",
        "mnemonic_lyrics": (
            "Forests breathe life, oceans clean the air,\n"
            "Reduce, reuse, recycle — show you care,\n"
            "Climate is changing, act before it's late,\n"
            "Protect our earth — that's humanity's fate."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Menilai",
            "illustrative_notes": (
                "Environmental issues include deforestation, pollution, climate change, and loss of biodiversity. "
                "Sustainable practices such as reducing waste, conserving energy, and protecting natural habitats are key themes. "
                "Understand the cause-and-effect relationship between human activity and environmental impact."
            ),
            "question": (
                "A factory discharges untreated chemical waste into a nearby river. "
                "Which is the MOST likely long-term consequence of this action?"
            ),
            "options": [
                "Increased fish population in the river",
                "Loss of aquatic biodiversity and contamination of the water supply",
                "Improved soil fertility along the riverbanks",
                "Higher rainfall in the surrounding area",
            ],
            "correct_answer": "Loss of aquatic biodiversity and contamination of the water supply",
            "distractor_rationale": {
                "Increased fish population in the river": (
                    "Chemical waste poisons aquatic life, reducing rather than increasing fish populations."
                ),
                "Improved soil fertility along the riverbanks": (
                    "Toxic chemicals degrade soil quality; they do not act as fertilisers."
                ),
                "Higher rainfall in the surrounding area": (
                    "Industrial waste discharge has no direct link to local precipitation patterns."
                ),
            },
        },
    },
    {
        "topic": "People and Work",
        "mnemonic_lyrics": (
            "Skills and passion, choose your path,\n"
            "Work with purpose, do the math,\n"
            "Communicate well, lead with care,\n"
            "Your career is built on what you dare."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Mengaplikasi",
            "illustrative_notes": (
                "This topic covers the world of work — career choices, job requirements, workplace communication, and professional qualities. "
                "Key vocabulary includes job roles, responsibilities, hard and soft skills, and workplace etiquette. "
                "Think about what employers value in candidates and what makes someone effective in their career."
            ),
            "question": (
                "An employer says: 'We need someone who can work well in a team, communicate clearly, and adapt to change.' "
                "Which category of skills is the employer PRIMARILY looking for?"
            ),
            "options": [
                "Technical skills",
                "Soft skills",
                "Digital literacy skills",
                "Academic qualifications",
            ],
            "correct_answer": "Soft skills",
            "distractor_rationale": {
                "Technical skills": (
                    "Technical skills refer to job-specific abilities like coding or accounting — "
                    "teamwork and communication are interpersonal, not technical."
                ),
                "Digital literacy skills": (
                    "Digital literacy is specifically about using technology; "
                    "the employer's list does not mention technology use."
                ),
                "Academic qualifications": (
                    "Academic qualifications are certificates and degrees, not personal qualities "
                    "like communication or adaptability."
                ),
            },
        },
    },
    {
        "topic": "Health and Wellness",
        "mnemonic_lyrics": (
            "Eat well, sleep right, move your feet,\n"
            "Mental health matters, find your beat,\n"
            "Balance your life, body and mind,\n"
            "Good habits today, your future's aligned."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Menilai",
            "illustrative_notes": (
                "Health and wellness covers physical health (diet, exercise, sleep), "
                "mental health (stress management, emotional wellbeing), and lifestyle choices. "
                "Understand the difference between healthy and unhealthy habits, and recognise factors that contribute to overall wellbeing. "
                "Prevention is better than cure."
            ),
            "question": (
                "Siti has been feeling tired, anxious, and unable to concentrate for several weeks due to exam pressure. "
                "What is the MOST appropriate first step she should take?"
            ),
            "options": [
                "Ignore the feelings and study harder",
                "Take sleeping pills to improve her rest",
                "Talk to a trusted adult or counsellor about her feelings",
                "Skip school until she feels better",
            ],
            "correct_answer": "Talk to a trusted adult or counsellor about her feelings",
            "distractor_rationale": {
                "Ignore the feelings and study harder": (
                    "Ignoring mental health symptoms worsens them over time; this does not address the root cause."
                ),
                "Take sleeping pills to improve her rest": (
                    "Self-medicating with sleeping pills is not safe without medical supervision "
                    "and does not address anxiety or stress."
                ),
                "Skip school until she feels better": (
                    "Avoidance can increase anxiety; seeking support is a healthier and more effective strategy."
                ),
            },
        },
    },
    {
        "topic": "Technology and Innovation",
        "mnemonic_lyrics": (
            "AI thinks, robots build and grow,\n"
            "Innovation fuels the world we know,\n"
            "Code and data, circuits bright,\n"
            "Tech transforms our daily life."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Menilai",
            "illustrative_notes": (
                "This topic explores how technology and innovation shape modern society — covering artificial intelligence, "
                "automation, digital communication, and ethical considerations. "
                "Understand both the benefits (efficiency, connectivity) and risks (privacy, job displacement, misinformation) "
                "of technological advancement."
            ),
            "question": (
                "A company replaces 50 factory workers with automated robots. "
                "Which statement BEST evaluates the impact of this change?"
            ),
            "options": [
                "It is entirely positive because robots make no mistakes",
                "It benefits the company financially but raises concerns about unemployment and workers' livelihoods",
                "It has no impact on society because new jobs will always be created immediately",
                "It is illegal in all countries to replace workers with machines",
            ],
            "correct_answer": "It benefits the company financially but raises concerns about unemployment and workers' livelihoods",
            "distractor_rationale": {
                "It is entirely positive because robots make no mistakes": (
                    "Robots can malfunction and require maintenance; "
                    "the social cost of unemployment is also a significant negative impact."
                ),
                "It has no impact on society because new jobs will always be created immediately": (
                    "Job displacement is not immediately offset — reskilling takes time and "
                    "not all displaced workers find new employment quickly."
                ),
                "It is illegal in all countries to replace workers with machines": (
                    "Automation is legal in most countries; the ethical debate is separate from legality."
                ),
            },
        },
    },
    {
        "topic": "Arts and Culture",
        "mnemonic_lyrics": (
            "Culture tells the stories of our past,\n"
            "Art speaks a language built to last,\n"
            "Dance, music, craft — identity glows,\n"
            "Through every brushstroke, a heritage shows."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Menganalisis",
            "illustrative_notes": (
                "Arts and culture encompasses traditional and contemporary art forms, Malaysian cultural heritage, "
                "literature, music, and performing arts. "
                "Understand how culture shapes identity and how artistic expression communicates values, history, and emotions. "
                "Consider the role of art in society and the importance of preserving cultural heritage."
            ),
            "question": (
                "A group of young Malaysians creates a street mural combining traditional batik patterns with modern graffiti styles. "
                "What does this artwork BEST represent?"
            ),
            "options": [
                "A rejection of Malaysian cultural values",
                "A fusion of traditional heritage with contemporary expression",
                "Evidence that traditional art is becoming less relevant",
                "A form of vandalism with no cultural significance",
            ],
            "correct_answer": "A fusion of traditional heritage with contemporary expression",
            "distractor_rationale": {
                "A rejection of Malaysian cultural values": (
                    "Incorporating traditional batik patterns shows respect for heritage, not rejection."
                ),
                "Evidence that traditional art is becoming less relevant": (
                    "Integrating traditional elements into modern art keeps heritage alive and relevant."
                ),
                "A form of vandalism with no cultural significance": (
                    "Street art that incorporates cultural symbols carries cultural meaning regardless of its medium."
                ),
            },
        },
    },
    {
        "topic": "Literature: Poems",
        "mnemonic_lyrics": (
            "Every line a feeling, every stanza a thought,\n"
            "Theme and tone — the meaning that's sought,\n"
            "Imagery paints pictures in your mind,\n"
            "Poetry's the truth that words help you find."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Menganalisis",
            "illustrative_notes": (
                "When analysing poems in KSSM English, focus on theme (central message), tone (poet's attitude), "
                "imagery (descriptive language that appeals to the senses), and poetic devices like "
                "personification, simile, metaphor, and repetition. "
                "Always support your analysis with evidence from the text."
            ),
            "question": (
                "Read this excerpt: 'The trees whispered secrets to the wind, / Bending low as though in prayer.' "
                "Which poetic device is PRIMARILY used here?"
            ),
            "options": [
                "Simile",
                "Personification",
                "Hyperbole",
                "Onomatopoeia",
            ],
            "correct_answer": "Personification",
            "distractor_rationale": {
                "Simile": (
                    "A simile compares using 'like' or 'as'; there is no such comparison word in this excerpt."
                ),
                "Hyperbole": (
                    "Hyperbole is an extreme exaggeration for effect; "
                    "the trees 'whispering' attributes human qualities, not exaggeration."
                ),
                "Onomatopoeia": (
                    "Onomatopoeia uses words that sound like what they describe (e.g. 'buzz', 'crash'); "
                    "'whispered' here gives trees human qualities, which is personification."
                ),
            },
        },
    },
    {
        "topic": "Literature: Short Stories",
        "mnemonic_lyrics": (
            "Setting, plot, and character combine,\n"
            "Conflict builds along the story's spine,\n"
            "Theme is the lesson the author leaves behind,\n"
            "Read between the lines for the truth you'll find."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Menganalisis",
            "illustrative_notes": (
                "Short stories contain key literary elements: plot (sequence of events), character (protagonist, antagonist), "
                "setting (time and place), conflict (internal or external), and theme (central message). "
                "The climax is the turning point of the story. "
                "Pay attention to how the author uses language to develop these elements."
            ),
            "question": (
                "In a short story, a young boy wants to prove his bravery to his friends "
                "but is terrified of going into the old house alone. "
                "This is an example of which type of conflict?"
            ),
            "options": [
                "Character vs. Nature",
                "Character vs. Society",
                "Character vs. Self",
                "Character vs. Character",
            ],
            "correct_answer": "Character vs. Self",
            "distractor_rationale": {
                "Character vs. Nature": (
                    "Character vs. Nature involves a struggle against natural forces like storms or wild animals, "
                    "not internal fear."
                ),
                "Character vs. Society": (
                    "Character vs. Society is about clashing with social norms or systems, "
                    "not an internal dilemma about courage."
                ),
                "Character vs. Character": (
                    "Character vs. Character involves a direct struggle between two characters; "
                    "here the boy is struggling with his own emotions."
                ),
            },
        },
    },
    {
        "topic": "Literature: Drama",
        "mnemonic_lyrics": (
            "Dialogue drives the drama on stage,\n"
            "Conflict peaks on every page,\n"
            "Stage directions set the scene just right,\n"
            "Theme shines through in every line of light."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Memahami",
            "illustrative_notes": (
                "Drama is a literary form written for performance. Key elements include dialogue (characters' speech), "
                "stage directions (instructions for actors), acts and scenes (structural divisions), "
                "character motivation (why characters behave as they do), and dramatic conflict. "
                "Understand how dialogue reveals character and advances the plot."
            ),
            "question": (
                "In a drama script, the text reads: "
                "'[MALIK enters stage left, looking over his shoulder nervously]'. "
                "What is this an example of?"
            ),
            "options": [
                "Dialogue",
                "Stage direction",
                "Soliloquy",
                "Aside",
            ],
            "correct_answer": "Stage direction",
            "distractor_rationale": {
                "Dialogue": (
                    "Dialogue is spoken words between characters; "
                    "this is a written instruction in brackets, not spoken."
                ),
                "Soliloquy": (
                    "A soliloquy is a long speech where a character speaks their thoughts aloud alone on stage; "
                    "this is a movement instruction."
                ),
                "Aside": (
                    "An aside is when a character briefly speaks directly to the audience; "
                    "this is a bracketed instruction about physical movement."
                ),
            },
        },
    },
    {
        "topic": "Literature: Novel",
        "mnemonic_lyrics": (
            "Chapter by chapter the story grows,\n"
            "Characters change as the narrative flows,\n"
            "Theme and symbol, author's voice,\n"
            "Every reader makes the novel their choice."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Menganalisis",
            "illustrative_notes": (
                "When studying a novel, examine plot structure (exposition, rising action, climax, falling action, resolution), "
                "character development (how characters change), themes (recurring ideas), "
                "the author's purpose, and literary techniques. "
                "A dynamic character changes significantly through the story, while a static character remains the same."
            ),
            "question": (
                "At the start of a novel, the protagonist is selfish and dishonest. "
                "By the end, he sacrifices his own comfort to help his community. "
                "What type of character is he?"
            ),
            "options": [
                "Antagonist",
                "Static character",
                "Dynamic character",
                "Foil character",
            ],
            "correct_answer": "Dynamic character",
            "distractor_rationale": {
                "Antagonist": (
                    "An antagonist is the character who opposes the protagonist; "
                    "this describes the protagonist's own transformation."
                ),
                "Static character": (
                    "A static character does not change throughout the story; "
                    "this character clearly undergoes significant growth."
                ),
                "Foil character": (
                    "A foil character exists to contrast with another character, "
                    "not to show personal change over time."
                ),
            },
        },
    },
    {
        "topic": "Grammar in Context",
        "mnemonic_lyrics": (
            "Tenses tell the time of what you say,\n"
            "Active voice cuts through the grey,\n"
            "Subject-verb agreement, keep it tight,\n"
            "Correct your grammar, write it right."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Mengaplikasi",
            "illustrative_notes": (
                "Grammar in context focuses on applying grammatical rules in real reading and writing situations. "
                "Key areas include tense consistency, subject-verb agreement, passive and active voice, "
                "sentence structure, punctuation, and parts of speech. "
                "Errors are identified by checking whether the grammar rule fits the meaning and context of the sentence."
            ),
            "question": "Choose the sentence that is grammatically CORRECT.",
            "options": [
                "The committee have decided to postpone the event.",
                "The committee has decided to postpone the event.",
                "The committee have decides to postpone the event.",
                "The committee has decide to postpone the event.",
            ],
            "correct_answer": "The committee has decided to postpone the event.",
            "distractor_rationale": {
                "The committee have decided to postpone the event.": (
                    "In Malaysian formal English, collective nouns like 'committee' take a singular verb — 'has' not 'have'."
                ),
                "The committee have decides to postpone the event.": (
                    "Using both 'have' (plural) and 'decides' (third-person singular) in the same verb phrase is a double error."
                ),
                "The committee has decide to postpone the event.": (
                    "After the auxiliary verb 'has', the main verb must be in past participle form ('decided'), not base form ('decide')."
                ),
            },
        },
    },
    {
        "topic": "Vocabulary Building",
        "mnemonic_lyrics": (
            "Root words hold the key to meaning's door,\n"
            "Prefix and suffix unlock so much more,\n"
            "Context clues guide you word by word,\n"
            "The richer your vocab, the clearer you're heard."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Mengaplikasi",
            "illustrative_notes": (
                "Building vocabulary involves understanding word meanings through context clues, root words, prefixes, and suffixes. "
                "Common prefixes: un- (not), re- (again), pre- (before), mis- (wrongly). "
                "Common suffixes: -tion (state/action), -ful (full of), -less (without). "
                "Use the surrounding sentence to infer meaning when you encounter unfamiliar words."
            ),
            "question": "The prefix 'mis-' is added to the word 'interpret'. What does 'misinterpret' mean?",
            "options": [
                "To interpret again",
                "To interpret before others",
                "To interpret incorrectly",
                "To interpret very clearly",
            ],
            "correct_answer": "To interpret incorrectly",
            "distractor_rationale": {
                "To interpret again": (
                    "The prefix 're-' means again (e.g. reinterpret), not 'mis-'."
                ),
                "To interpret before others": (
                    "The prefix 'pre-' means before (e.g. preview); 'mis-' specifically signals an error or wrong action."
                ),
                "To interpret very clearly": (
                    "'Mis-' adds a negative meaning, not an intensifier — it implies wrongness, not clarity."
                ),
            },
        },
    },
    {
        "topic": "Society and Community",
        "mnemonic_lyrics": (
            "Together we build a stronger ground,\n"
            "Respect and duty all around,\n"
            "Volunteer, contribute, play your part,\n"
            "A healthy community starts in the heart."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Menilai",
            "illustrative_notes": (
                "Society and community covers topics like civic responsibility, volunteerism, "
                "social issues (poverty, inequality, discrimination), community development, "
                "and the roles of individuals in society. "
                "Understand how individuals and groups can positively contribute to their communities "
                "and what challenges undermine social cohesion."
            ),
            "question": (
                "A neighbourhood experiences rising crime rates. "
                "Which approach would MOST effectively address the root cause of the problem?"
            ),
            "options": [
                "Building higher fences around individual homes",
                "Ignoring the issue and hoping it resolves itself",
                "Organising community watch programmes and addressing socioeconomic inequality",
                "Banning all public gatherings in the area",
            ],
            "correct_answer": "Organising community watch programmes and addressing socioeconomic inequality",
            "distractor_rationale": {
                "Building higher fences around individual homes": (
                    "Individual physical barriers are reactive and do not address the underlying social causes of crime."
                ),
                "Ignoring the issue and hoping it resolves itself": (
                    "Neglecting a social problem allows it to escalate rather than resolve."
                ),
                "Banning all public gatherings in the area": (
                    "Restricting public assembly reduces community bonding and does not address why crime is occurring."
                ),
            },
        },
    },
    {
        "topic": "Global Issues and Current Affairs",
        "mnemonic_lyrics": (
            "Climate, conflict, poverty and more,\n"
            "Global problems need solutions we explore,\n"
            "Stay informed, think critically each day,\n"
            "World citizens must have a say."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Menilai",
            "illustrative_notes": (
                "Global issues include climate change, human rights, poverty, refugees, gender equality, and international conflicts. "
                "Understand the interconnected nature of these problems and the roles of international organisations "
                "(UN, WHO, UNICEF) in addressing them. "
                "Critical reading of news articles helps distinguish fact from opinion."
            ),
            "question": (
                "A newspaper headline reads: 'Government MUST act NOW to stop climate disaster.' "
                "Which feature of this headline indicates it is an OPINION rather than a fact?"
            ),
            "options": [
                "It mentions the government",
                "It uses the word 'climate'",
                "It uses emotive language like 'MUST' and 'disaster' to express urgency",
                "It is written with capital letters for emphasis",
            ],
            "correct_answer": "It uses emotive language like 'MUST' and 'disaster' to express urgency",
            "distractor_rationale": {
                "It mentions the government": (
                    "Mentioning the government is neutral — governments are commonly referenced in factual news articles too."
                ),
                "It uses the word 'climate'": (
                    "The word 'climate' is a neutral scientific term and does not make a statement an opinion."
                ),
                "It is written with capital letters for emphasis": (
                    "Capitalisation is a stylistic choice and does not determine whether a statement is fact or opinion."
                ),
            },
        },
    },
    {
        "topic": "Science and Technology",
        "mnemonic_lyrics": (
            "Hypothesis, test, observe, conclude,\n"
            "Science and tech shape the world's attitude,\n"
            "Innovate wisely, question what you know,\n"
            "Data and evidence help knowledge grow."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Menganalisis",
            "illustrative_notes": (
                "This topic explores how scientific discoveries and technological advances affect everyday life and society. "
                "Key themes include the scientific method, ethical considerations in research, digital transformation, "
                "healthcare advances, and environmental technology. "
                "Understand the difference between scientific facts and emerging theories."
            ),
            "question": (
                "Scientists concluded that a new drug reduces fever in 80% of patients tested. "
                "Which additional information is MOST important before the drug is approved for public use?"
            ),
            "options": [
                "The colour and shape of the pill",
                "Whether the scientists enjoyed conducting the research",
                "Potential side effects and results from large-scale clinical trials",
                "The cost of the laboratory equipment used",
            ],
            "correct_answer": "Potential side effects and results from large-scale clinical trials",
            "distractor_rationale": {
                "The colour and shape of the pill": (
                    "Physical appearance is irrelevant to a drug's safety and efficacy."
                ),
                "Whether the scientists enjoyed conducting the research": (
                    "Researcher satisfaction does not validate scientific findings."
                ),
                "The cost of the laboratory equipment used": (
                    "Equipment cost does not determine whether a drug is safe or effective for patients."
                ),
            },
        },
    },
    {
        "topic": "Travel and Adventure",
        "mnemonic_lyrics": (
            "Pack your bags, the world awaits,\n"
            "Cross the borders, open the gates,\n"
            "New cultures, sights and languages too,\n"
            "Every journey shapes a brand new you."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Mengaplikasi",
            "illustrative_notes": (
                "Travel and adventure topics cover travel writing, describing places, cultural exchange, "
                "planning and preparation, and the personal growth that comes from experiencing different cultures. "
                "Key language skills include writing travel blogs, understanding itineraries, "
                "and using descriptive vocabulary for places, emotions, and experiences."
            ),
            "question": (
                "A travel writer describes a market as: "
                "'A riot of colour erupted before me — towers of spices, bolts of silk, "
                "and the air thick with the scent of jasmine.' "
                "What is the PRIMARY purpose of this descriptive language?"
            ),
            "options": [
                "To provide factual information about market prices",
                "To create a vivid sensory experience for the reader",
                "To give directions to the market",
                "To warn travellers about the dangers of the market",
            ],
            "correct_answer": "To create a vivid sensory experience for the reader",
            "distractor_rationale": {
                "To provide factual information about market prices": (
                    "The description uses imagery and sensory language, not data or prices."
                ),
                "To give directions to the market": (
                    "Descriptive writing evokes atmosphere; directional writing uses landmarks and distances."
                ),
                "To warn travellers about the dangers of the market": (
                    "The language is celebratory and immersive, conveying beauty — not warning or danger."
                ),
            },
        },
    },
    {
        "topic": "Media and Communication",
        "mnemonic_lyrics": (
            "Scroll and share, but check it's true,\n"
            "Media shapes the world's point of view,\n"
            "Bias hides in headlines bright,\n"
            "Critical thinking is your right."
        ),
        "anchor_question": {
            "question_type": "mcq",
            "kbat_level": "Menilai",
            "illustrative_notes": (
                "Media and communication covers different media types (print, digital, social media), "
                "communication purposes (inform, persuade, entertain), media bias, fake news, "
                "and responsible digital citizenship. "
                "Understanding how media constructs messages helps you evaluate content critically. "
                "Look for hidden bias, language choices, and the intended audience."
            ),
            "question": (
                "Two news websites report the same protest. "
                "Website A: 'Brave citizens stand up for their rights.' "
                "Website B: 'Troublemakers disrupt city streets.' "
                "What does the difference between these headlines BEST illustrate?"
            ),
            "options": [
                "That one website is always more accurate than the other",
                "That protests are always controversial events",
                "That media language choices reflect bias and shape the reader's perception",
                "That headlines must always be objective and factual",
            ],
            "correct_answer": "That media language choices reflect bias and shape the reader's perception",
            "distractor_rationale": {
                "That one website is always more accurate than the other": (
                    "We cannot determine accuracy from headlines alone — both express a perspective, not necessarily facts."
                ),
                "That protests are always controversial events": (
                    "The point is not about protests but about how the same event can be framed differently through word choice."
                ),
                "That headlines must always be objective and factual": (
                    "These headlines demonstrate the opposite — that headlines often carry subjective framing."
                ),
            },
        },
    },
]


def main():
    print(f"Fetching existing topic_anchors for '{SUBJECT}' in {LANGUAGE}...")
    res = supabase.table("topic_anchors").select("topic, language")\
        .eq("language", LANGUAGE).execute()
    cached = {row["topic"] for row in (res.data or [])}
    print(f"  {len(cached)} anchor(s) already cached.\n")

    to_seed = [a for a in ANCHORS if a["topic"] not in cached]
    already_done = len(ANCHORS) - len(to_seed)
    print(f"Plan: {len(to_seed)} to insert, {already_done} already cached.\n")

    if not to_seed:
        print("Nothing to do — all Bahasa Inggeris anchors already cached.")
        return

    ok = fail = 0
    for anchor in to_seed:
        topic = anchor["topic"]
        print(f"  Inserting: {topic} ...", end=" ", flush=True)
        try:
            supabase.table("topic_anchors").upsert({
                "subject": SUBJECT,
                "topic": topic,
                "language": LANGUAGE,
                "mnemonic_lyrics": anchor["mnemonic_lyrics"],
                "anchor_question": anchor["anchor_question"],
                "audio_url": FALLBACK_AUDIO,
                "video_broll": FALLBACK_VIDEO,
            }, on_conflict="topic,language").execute()
            print("✓")
            ok += 1
        except Exception as e:
            print(f"✗  {e}")
            fail += 1

    print(f"\nDone. {ok} inserted, {fail} failed.")


if __name__ == "__main__":
    main()
