#!/usr/bin/env bash
# One-time script: clone the Lovable frontend and wire up the .env.
# Run as root from anywhere. Safe to re-run — skips clone if already present.
#
# Usage: bash /root/kuasaprestij/deploy/frontend_setup.sh

set -euo pipefail

FRONTEND_DIR="/root/frontend/learn-play-shine-96"
REPO_URL="https://github.com/alvinauh/learn-play-shine-96.git"
API_URL="https://api.kuasa.tech:8443"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

# ── 1. Clone ────────────────────────────────────────────────────────────────
if [ -d "$FRONTEND_DIR/.git" ]; then
    log "Repo already cloned at $FRONTEND_DIR — pulling latest instead."
    git -C "$FRONTEND_DIR" pull origin main --ff-only
else
    log "Cloning $REPO_URL → $FRONTEND_DIR"
    mkdir -p "$(dirname "$FRONTEND_DIR")"
    git clone "$REPO_URL" "$FRONTEND_DIR"
fi

# ── 2. Write .env (only if it doesn't exist yet) ────────────────────────────
ENV_FILE="$FRONTEND_DIR/.env"
if [ -f "$ENV_FILE" ]; then
    log ".env already exists — skipping. Edit manually if VITE_API_BASE_URL is wrong."
else
    log "Writing $ENV_FILE"
    # Pull Supabase values from the backend .env so we stay in sync.
    BACKEND_ENV="/root/kuasaprestij/.env"
    SB_URL=$(grep -E '^SUPABASE_URL=' "$BACKEND_ENV" | cut -d= -f2- | tr -d '"')
    SB_KEY=$(grep -E '^SUPABASE_KEY=' "$BACKEND_ENV" | cut -d= -f2- | tr -d '"')

    cat > "$ENV_FILE" <<EOF
# Auto-generated by frontend_setup.sh — edit VITE_API_BASE_URL if your domain changes.
SUPABASE_URL="${SB_URL}"
SUPABASE_PROJECT_ID="bvttqyyzmtlsddpzjpnk"
SUPABASE_PUBLISHABLE_KEY="${SB_KEY}"
VITE_SUPABASE_URL="${SB_URL}"
VITE_SUPABASE_PROJECT_ID="bvttqyyzmtlsddpzjpnk"
VITE_SUPABASE_PUBLISHABLE_KEY="${SB_KEY}"
VITE_API_BASE_URL="${API_URL}"
EOF
    log "Written. Check $ENV_FILE before starting."
fi

# ── 3. Install dependencies ─────────────────────────────────────────────────
log "Installing npm dependencies (this may take a minute)..."
cd "$FRONTEND_DIR"
npm install --legacy-peer-deps

# ── 4. Install and enable the systemd service ────────────────────────────────
log "Installing systemd units..."
cp /root/kuasaprestij/deploy/kuasaprestij-frontend.service        /etc/systemd/system/
cp /root/kuasaprestij/deploy/kuasaprestij-frontend-pull.service   /etc/systemd/system/
cp /root/kuasaprestij/deploy/kuasaprestij-frontend-pull.timer     /etc/systemd/system/

systemctl daemon-reload
systemctl enable --now kuasaprestij-frontend
systemctl enable --now kuasaprestij-frontend-pull.timer

log "Done. Check status with: systemctl status kuasaprestij-frontend"
log "Tail logs with:          journalctl -u kuasaprestij-frontend -f"
