-- KuasaPrestij schema for moeagentic / g1_p1
-- Adapted from cloudsql_schema.sql:
--   - all objects in g1_p1 schema (no public/auth schemas available)
--   - vector(768) replaced with float8[] (pgvector not installed)
--   - auth.users FKs removed (no auth schema available)
--   - gen_random_uuid() used directly (built-in Postgres 18.6)

SET search_path TO g1_p1;

-- ── Stub auth.uid() inside g1_p1 (used by RLS-style functions) ───────────────
CREATE OR REPLACE FUNCTION g1_p1.auth_uid() RETURNS uuid
  LANGUAGE sql STABLE
AS $$
  SELECT nullif(current_setting('request.jwt.claims', true)::json->>'sub', '')::uuid;
$$;

-- ── Tables ────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS g1_p1.profiles (
  id uuid PRIMARY KEY,
  full_name text,
  role text DEFAULT 'student' CHECK (role = ANY (ARRAY['student','teacher','admin'])),
  school text,
  grade text,
  created_at timestamptz DEFAULT now(),
  preferences jsonb DEFAULT '{}'::jsonb
);

-- Test-user stub (student_id "undefined" remaps here)
INSERT INTO g1_p1.profiles (id, full_name, role)
VALUES ('00000000-0000-0000-0000-000000000001', 'Test Student', 'student')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS g1_p1.students (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  grade_level text NOT NULL,
  active_subjects text[] DEFAULT '{}',
  created_at timestamptz DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS g1_p1.syllabus_embeddings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content text,
  metadata jsonb,
  embedding float8[],
  source_type text DEFAULT 'textbook'
);

CREATE TABLE IF NOT EXISTS g1_p1.generated_lessons (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  topic text NOT NULL,
  subject text NOT NULL,
  form_level integer NOT NULL,
  language text DEFAULT 'English',
  title text,
  dskp_code text,
  notes_content text,
  notes_json jsonb,
  created_at timestamptz DEFAULT now(),
  UNIQUE (topic, subject, form_level, language)
);

CREATE TABLE IF NOT EXISTS g1_p1.classrooms (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  subject text,
  invite_code text NOT NULL DEFAULT substring(gen_random_uuid()::text, 1, 8),
  teacher_id uuid NOT NULL,
  created_at timestamptz DEFAULT now(),
  theme text,
  wallpaper text,
  UNIQUE (invite_code)
);

CREATE TABLE IF NOT EXISTS g1_p1.quizzes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lesson_id uuid REFERENCES g1_p1.generated_lessons(id),
  topic text,
  questions_jsonb jsonb NOT NULL,
  difficulty_level text DEFAULT 'medium',
  question_type text DEFAULT 'mcq',
  num_questions integer,
  language text DEFAULT 'English',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS g1_p1.quiz_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  topic text NOT NULL,
  subject text NOT NULL,
  language text DEFAULT 'English',
  question_type text DEFAULT 'mcq',
  is_adaptive boolean DEFAULT false,
  lesson_id uuid REFERENCES g1_p1.generated_lessons(id),
  current_draft jsonb,
  answered_count integer DEFAULT 0,
  mastery_score numeric DEFAULT 0.0,
  status text DEFAULT 'active' CHECK (status = ANY (ARRAY['active','complete'])),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  prefetched_draft jsonb,
  wrong_count integer DEFAULT 0,
  streak integer DEFAULT 0,
  score integer DEFAULT 0,
  last_penalty_count integer DEFAULT -100
);

CREATE TABLE IF NOT EXISTS g1_p1.topic_anchors (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subject text,
  topic text,
  mnemonic_lyrics text,
  audio_url text,
  anchor_question jsonb,
  created_at timestamptz DEFAULT now(),
  video_broll text,
  language text DEFAULT 'English',
  h5p_content jsonb,
  question_bank jsonb DEFAULT '[]'::jsonb,
  form_level integer DEFAULT 4,
  diagram_svg text,
  worked_example text,
  interactive_content jsonb,
  UNIQUE (topic, language, form_level)
);

CREATE TABLE IF NOT EXISTS g1_p1.dskp_mastery (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL REFERENCES g1_p1.profiles(id),
  curriculum_tag text NOT NULL,
  topic text NOT NULL,
  mastery_level float8 DEFAULT 0.0,
  last_assessed_at timestamptz,
  next_review_at timestamptz,
  UNIQUE (student_id, curriculum_tag, topic)
);

CREATE TABLE IF NOT EXISTS g1_p1.event_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL REFERENCES g1_p1.profiles(id),
  topic text NOT NULL,
  kbat_level text NOT NULL,
  is_correct boolean NOT NULL,
  time_spent_seconds integer,
  diagnostic_tag text,
  created_at timestamptz DEFAULT timezone('utc', now()),
  error_category text,
  root_cause text,
  intervention text,
  subject text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS g1_p1.media_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  curriculum_tag text NOT NULL,
  topic text NOT NULL,
  media_type text NOT NULL,
  asset_url text NOT NULL,
  created_at timestamptz DEFAULT timezone('utc', now()),
  UNIQUE (curriculum_tag, topic, media_type)
);

CREATE TABLE IF NOT EXISTS g1_p1.student_daily_report (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT timezone('utc', now()),
  student_id uuid,
  student_name text,
  subject text NOT NULL,
  progress integer DEFAULT 0,
  class_average integer DEFAULT 0,
  topics_mastered text[] DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS g1_p1.chat_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  lesson_id uuid REFERENCES g1_p1.generated_lessons(id),
  role text NOT NULL CHECK (role = ANY (ARRAY['student','tutor'])),
  content text NOT NULL,
  created_at timestamptz DEFAULT now(),
  session_id uuid REFERENCES g1_p1.quiz_sessions(id)
);

CREATE TABLE IF NOT EXISTS g1_p1.remediation_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  subject text NOT NULL,
  topic text NOT NULL,
  priority_score numeric DEFAULT 0.5,
  reason text,
  error_categories text[],
  root_causes text[],
  suggested_intervention text,
  status text DEFAULT 'active' CHECK (status = ANY (ARRAY['active','done'])),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (student_id, topic)
);

CREATE TABLE IF NOT EXISTS g1_p1.game_scores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  quiz_session_id uuid REFERENCES g1_p1.quiz_sessions(id),
  game_type text NOT NULL CHECK (game_type = ANY (ARRAY['catch_stars','dino_runner','flappy_bird'])),
  result text NOT NULL CHECK (result = ANY (ARRAY['win','loss'])),
  duration_ms integer,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS g1_p1.user_feedback (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid,
  quiz_id uuid REFERENCES g1_p1.quizzes(id),
  lesson_id uuid REFERENCES g1_p1.generated_lessons(id),
  test_score numeric,
  suggested_improvements text,
  raw_payload jsonb,
  status text DEFAULT 'pending' CHECK (status = ANY (ARRAY['pending','in_progress','processed','dismissed','no_action'])),
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS g1_p1.classroom_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  classroom_id uuid NOT NULL REFERENCES g1_p1.classrooms(id),
  student_id uuid NOT NULL,
  joined_at timestamptz DEFAULT now(),
  UNIQUE (classroom_id, student_id)
);

CREATE TABLE IF NOT EXISTS g1_p1.assignments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  classroom_id uuid NOT NULL REFERENCES g1_p1.classrooms(id),
  teacher_id uuid NOT NULL,
  title text NOT NULL,
  instructions text,
  subject text,
  topic text,
  form_level integer,
  question_type text DEFAULT 'mcq',
  due_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS g1_p1.assigned_tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  subject text,
  topic text,
  task_type text DEFAULT 'quiz',
  instructions text,
  teacher_note text,
  error_context text[],
  priority_score numeric,
  status text DEFAULT 'pending',
  assigned_at timestamptz DEFAULT now(),
  started_at timestamptz,
  completed_at timestamptz,
  due_at timestamptz,
  session_id uuid,
  lesson_id uuid REFERENCES g1_p1.generated_lessons(id),
  quiz_id uuid
);

CREATE TABLE IF NOT EXISTS g1_p1.agent_traces (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  trace_id uuid NOT NULL,
  node text NOT NULL,
  label text DEFAULT '',
  duration_ms float8,
  status text DEFAULT 'ok',
  provider text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS g1_p1.feedback_quality_audit (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  result jsonb NOT NULL,
  scripts_analyzed integer,
  total_acts integer,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS g1_p1.app_errors (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid,
  level text DEFAULT 'error',
  message text NOT NULL,
  source text,
  url text,
  stack text,
  context jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS g1_p1.teacher_chat (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  teacher_id uuid DEFAULT '00000000-0000-0000-0000-000000000001',
  thread_id uuid DEFAULT '00000000-0000-0000-0000-000000000001',
  role text NOT NULL CHECK (role = ANY (ARRAY['teacher','assistant'])),
  content text DEFAULT '',
  artifacts jsonb DEFAULT '[]'::jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS g1_p1.rph_documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  title text NOT NULL,
  mata_pelajaran text NOT NULL,
  tingkatan text NOT NULL,
  tarikh date,
  masa text,
  bilangan_murid integer,
  tema text,
  tajuk text NOT NULL,
  standard_kandungan text[],
  standard_pembelajaran text[],
  objektif text[],
  nilai_murni text[],
  elemen_merentas_kurikulum text[],
  bahan_bantu_mengajar text[],
  fasa_induksi_set jsonb,
  fasa_penyampaian jsonb,
  fasa_amali jsonb,
  fasa_penghasilan jsonb,
  fasa_penutup jsonb,
  impak text,
  catatan text,
  source_files text[],
  share_token uuid DEFAULT gen_random_uuid(),
  status text DEFAULT 'draft' CHECK (status = ANY (ARRAY['draft','complete'])),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS g1_p1.aita_games (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  rph_id uuid REFERENCES g1_p1.rph_documents(id),
  title text NOT NULL,
  game_type text NOT NULL CHECK (game_type = ANY (ARRAY['flappy','dino','catch','connector','sentence','kahoot','wordsearch'])),
  config jsonb DEFAULT '{}'::jsonb,
  share_token uuid DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS g1_p1.aita_game_assignments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id uuid NOT NULL REFERENCES g1_p1.aita_games(id),
  classroom_id uuid,
  teacher_id uuid NOT NULL,
  due_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS g1_p1.aita_game_scores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id uuid NOT NULL REFERENCES g1_p1.aita_games(id),
  student_id uuid,
  player_name text,
  score integer DEFAULT 0,
  completed_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS g1_p1.rph_shares (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rph_id uuid NOT NULL REFERENCES g1_p1.rph_documents(id),
  shared_by uuid NOT NULL,
  share_token uuid DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now()
);

-- Coins / perks
CREATE TABLE IF NOT EXISTS g1_p1.student_coins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL REFERENCES g1_p1.profiles(id),
  balance integer DEFAULT 0,
  updated_at timestamptz DEFAULT now(),
  UNIQUE (student_id)
);

CREATE TABLE IF NOT EXISTS g1_p1.coin_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  amount integer NOT NULL,
  reason text,
  meta jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS g1_p1.student_perks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  perk_id text NOT NULL,
  purchased_at timestamptz DEFAULT now(),
  used_at timestamptz,
  UNIQUE (student_id, perk_id)
);

CREATE TABLE IF NOT EXISTS g1_p1.question_skips (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  topic text,
  subject text,
  skipped_at timestamptz DEFAULT now()
);

-- ── Indexes ───────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_agent_traces_created_at    ON g1_p1.agent_traces (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_traces_node          ON g1_p1.agent_traces (node, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_traces_trace_id      ON g1_p1.agent_traces (trace_id);
CREATE INDEX IF NOT EXISTS idx_app_errors_created         ON g1_p1.app_errors (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_assigned_tasks_status      ON g1_p1.assigned_tasks (status);
CREATE INDEX IF NOT EXISTS idx_assigned_tasks_student     ON g1_p1.assigned_tasks (student_id);
CREATE INDEX IF NOT EXISTS idx_assignments_classroom      ON g1_p1.assignments (classroom_id);
CREATE INDEX IF NOT EXISTS idx_chat_history_student       ON g1_p1.chat_history (student_id, lesson_id, created_at);
CREATE INDEX IF NOT EXISTS idx_chat_history_session       ON g1_p1.chat_history (student_id, session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_game_scores_student        ON g1_p1.game_scores (student_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lessons_topic_subject      ON g1_p1.generated_lessons (topic, subject, form_level);
CREATE INDEX IF NOT EXISTS idx_quiz_sessions_student      ON g1_p1.quiz_sessions (student_id, status);
CREATE INDEX IF NOT EXISTS idx_quizzes_lesson_id          ON g1_p1.quizzes (lesson_id);
CREATE INDEX IF NOT EXISTS idx_remediation_student        ON g1_p1.remediation_plans (student_id, status, priority_score DESC);
CREATE INDEX IF NOT EXISTS idx_teacher_chat_thread        ON g1_p1.teacher_chat (teacher_id, thread_id, created_at);
CREATE INDEX IF NOT EXISTS idx_event_logs_student         ON g1_p1.event_logs (student_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_dskp_mastery_student       ON g1_p1.dskp_mastery (student_id, curriculum_tag);
CREATE INDEX IF NOT EXISTS idx_syllabus_source_type       ON g1_p1.syllabus_embeddings (source_type);

-- ── Functions ─────────────────────────────────────────────────────────────────

-- Cosine similarity for float8[] (replaces pgvector <=> operator)
CREATE OR REPLACE FUNCTION g1_p1.cosine_similarity(a float8[], b float8[])
RETURNS float8 LANGUAGE sql IMMUTABLE STRICT AS $$
  SELECT
    (SELECT SUM(x * y) FROM UNNEST(a, b) AS t(x, y)) /
    NULLIF(
      SQRT((SELECT SUM(x * x) FROM UNNEST(a) AS t(x))) *
      SQRT((SELECT SUM(y * y) FROM UNNEST(b) AS t(y))),
      0
    );
$$;

-- PostgREST RPC: match_syllabus_embeddings (called by retriever_node)
CREATE OR REPLACE FUNCTION g1_p1.match_syllabus_embeddings(
  query_embedding float8[],
  match_threshold float8,
  match_count integer
)
RETURNS TABLE(id bigint, content text, metadata jsonb, similarity float8)
LANGUAGE sql STABLE AS $$
  SELECT
    se.id,
    se.content,
    se.metadata,
    g1_p1.cosine_similarity(se.embedding, query_embedding) AS similarity
  FROM g1_p1.syllabus_embeddings se
  WHERE g1_p1.cosine_similarity(se.embedding, query_embedding) > match_threshold
  ORDER BY g1_p1.cosine_similarity(se.embedding, query_embedding) DESC
  LIMIT match_count;
$$;

-- Alias kept for any callers using old name
CREATE OR REPLACE FUNCTION g1_p1.match_syllabus(
  query_embedding float8[],
  match_threshold float8,
  match_count integer
)
RETURNS TABLE(id bigint, content text, metadata jsonb, similarity float8)
LANGUAGE sql STABLE AS $$
  SELECT * FROM g1_p1.match_syllabus_embeddings(query_embedding, match_threshold, match_count);
$$;

-- Mastery upsert (called by mastery_updater_node)
CREATE OR REPLACE FUNCTION g1_p1.increment_mastery(
  p_student_id uuid,
  p_topic text,
  p_subject text,
  p_delta float8,
  p_last_assessed_at timestamptz,
  p_next_review_at timestamptz
)
RETURNS float8 LANGUAGE plpgsql AS $$
DECLARE
  new_val float8;
BEGIN
  INSERT INTO g1_p1.dskp_mastery
    (student_id, curriculum_tag, topic, mastery_level, last_assessed_at, next_review_at)
  VALUES
    (p_student_id, p_subject, p_topic,
     GREATEST(0.0, LEAST(1.0, p_delta)),
     p_last_assessed_at, p_next_review_at)
  ON CONFLICT (student_id, curriculum_tag, topic) DO UPDATE SET
    mastery_level    = GREATEST(0.0, LEAST(1.0, g1_p1.dskp_mastery.mastery_level + p_delta)),
    last_assessed_at = EXCLUDED.last_assessed_at,
    next_review_at   = EXCLUDED.next_review_at
  RETURNING mastery_level INTO new_val;
  RETURN new_val;
END;
$$;

CREATE OR REPLACE FUNCTION g1_p1.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- ── Triggers ──────────────────────────────────────────────────────────────────
DROP TRIGGER IF EXISTS set_quiz_sessions_updated_at ON g1_p1.quiz_sessions;
CREATE TRIGGER set_quiz_sessions_updated_at
  BEFORE UPDATE ON g1_p1.quiz_sessions
  FOR EACH ROW EXECUTE FUNCTION g1_p1.set_updated_at();

DROP TRIGGER IF EXISTS set_remediation_updated_at ON g1_p1.remediation_plans;
CREATE TRIGGER set_remediation_updated_at
  BEFORE UPDATE ON g1_p1.remediation_plans
  FOR EACH ROW EXECUTE FUNCTION g1_p1.set_updated_at();

DROP TRIGGER IF EXISTS update_rph_updated_at ON g1_p1.rph_documents;
CREATE TRIGGER update_rph_updated_at
  BEFORE UPDATE ON g1_p1.rph_documents
  FOR EACH ROW EXECUTE FUNCTION g1_p1.set_updated_at();
