-- Add SVG diagram column to topic_anchors.
-- Safe to re-run (IF NOT EXISTS guard).
-- Apply in Supabase SQL Editor (project bvttqyyzmtlsddpzjpnk).

ALTER TABLE topic_anchors
    ADD COLUMN IF NOT EXISTS diagram_svg text;

COMMENT ON COLUMN topic_anchors.diagram_svg IS
    'AI-generated SVG diagram for the topic. Stored as raw SVG XML text. '
    'Generated by seed_diagrams.py via claude -p. Returned in /start_session '
    'as diagram_svg for frontend to render above the question card.';
