-- Add worked_example column to topic_anchors.
-- Safe to re-run (IF NOT EXISTS guard).
-- Apply in Supabase SQL Editor (project bvttqyyzmtlsddpzjpnk).

ALTER TABLE topic_anchors
    ADD COLUMN IF NOT EXISTS worked_example text;

COMMENT ON COLUMN topic_anchors.worked_example IS
    'Step-by-step worked example for the topic. Format is subject-appropriate: '
    'equations for Math/Physics, annotated passage for BM/English, etc. '
    'Generated by seed_worked_examples.py. Shown in the feedback sheet after wrong answers.';
